/* eslint-disable no-var -- `declare var` is required so the globals appear on
   `typeof globalThis` (guardian.ts assigns them via self.*); `declare let/const`
   would not attach them to globalThis. */
/**
 * Cross-file globals of the Aionda Mail browser extension.
 *
 * The extension keeps the classic-script architecture: every entrypoint in
 * ts/ is bundled to its own IIFE file (same path as the old .js file) and the
 * files communicate exclusively via globals (importScripts in the service
 * worker, <script> tags in the HTML pages).
 *
 * IMPORTANT for producers: esbuild wraps each bundle in an IIFE, so top-level
 * declarations are NOT global anymore. Every symbol listed here MUST be
 * explicitly assigned to globalThis by the file that defines it, e.g.
 *   Object.assign(globalThis, { callAPI, isPAT });
 * Mutable state (e.g. API_BASE_URL) must be exposed via
 *   Object.defineProperty(globalThis, "API_BASE_URL", { get: () => apiBaseUrl });
 *
 * Do not edit this file from porting agents - additional globals go into a
 * separate <area>.globals.d.ts next to the producing module.
 */

/** Firefox exposes `browser`, Chrome only `chrome`; both are MV3-promise-based. */
declare const browser: typeof chrome;

/** Available in the MV3 service worker (classic, non-module). */
declare function importScripts(...urls: string[]): void;

/* ------------------------------------------------------------------ *
 * api.ts                                                              *
 * ------------------------------------------------------------------ */

/** Generic API response: known fields typed, everything else unknown. */
interface TmApiResponse {
    session_id?: string;
    domain_name_list?: string[] | Record<string, unknown>;
    real_email_list?: Record<string, unknown>;
    error?: string;
    error_code?: number;
    data?: Record<string, unknown>;
    [key: string]: unknown;
}

declare function callAPI(data: Record<string, unknown>, json?: Record<string, unknown> | null): Promise<TmApiResponse>;
declare function isPAT(password: string): boolean;
declare function createAccessToken(sessionId: string, tokenName: string): Promise<TmApiResponse>;
declare function getApiBaseUrl(): Promise<string>;
declare function loadApiBaseUrl(): Promise<string>;
/** Manager-Tab oeffnen: POST-Login (PAT-OPAQUE bzw. classic) setzt das Session-Cookie, URL bleibt clean. */
declare function openAddressManagerAuthenticated(): Promise<void>;
/** Live value - exposed by api.ts via a defineProperty getter. */
declare const API_BASE_URL: string;
declare const PREFIXES: string[];

/* ------------------------------------------------------------------ *
 * guardian.ts - state shared with background.ts via self.*            *
 * ------------------------------------------------------------------ */

interface TmSecurityStatus {
    status: string;
    verified: number;
    unsigned: number;
    failed: unknown[];
    [key: string]: unknown;
}

declare var guardianInitialized: boolean;
declare var guardianEnabled: boolean;
declare var ed25519Supported: boolean | null;
declare var publicKeys: Map<string, CryptoKey>;
declare var tabSecurityStatus: Map<number, TmSecurityStatus>;
declare function isProtectedHost(hostname: string): boolean;
declare function initGuardian(): Promise<void>;
